di_bridge:
  definitions:
    - '%kernel.project_dir%/vendor/teknoo/east-foundation/src/di.php'
    - '%kernel.project_dir%/vendor/teknoo/east-foundation/infrastructures/symfony/Resources/config/di.php'
    - '%kernel.project_dir%/vendor/teknoo/east-website/src/di.php'
    - '%kernel.project_dir%/vendor/teknoo/east-website/infrastructures/doctrine/di.php'
    - '%kernel.project_dir%/vendor/teknoo/east-website/infrastructures/symfony/Resources/config/di.php'
    - '%kernel.project_dir%/vendor/teknoo/east-website/infrastructures/di.php'
    - '%kernel.project_dir%/vendor/teknoo/east-paas/src/di.php'
    - '%kernel.project_dir%/vendor/teknoo/east-paas/infrastructures/Doctrine/di.php'
    - '%kernel.project_dir%/vendor/teknoo/east-paas/infrastructures/Flysystem/di.php'
    - '%kernel.project_dir%/vendor/teknoo/east-paas/infrastructures/Git/di.php'
    - '%kernel.project_dir%/vendor/teknoo/east-paas/infrastructures/Kubernetes/di.php'
    - '%kernel.project_dir%/vendor/teknoo/east-paas/infrastructures/Docker/di.php'
    - '%kernel.project_dir%/vendor/teknoo/east-paas/infrastructures/Composer/di.php'
    - '%kernel.project_dir%/vendor/teknoo/east-paas/infrastructures/Symfony/Components/di.php'
    - '%kernel.project_dir%/config/di.php'
  import:
    Doctrine\Persistence\ObjectManager: 'doctrine_mongodb.odm.default_document_manager'
