di_bridge:
  definitions:
    - '%kernel.project_dir%/vendor/teknoo/east-paas/src/di.php'
    - '%kernel.project_dir%/vendor/teknoo/east-paas/infrastructures/Doctrine/di.php'
    - '%kernel.project_dir%/vendor/teknoo/east-paas/infrastructures/Flysystem/di.php'
    - '%kernel.project_dir%/vendor/teknoo/east-paas/infrastructures/Git/di.php'
    - '%kernel.project_dir%/vendor/teknoo/east-paas/infrastructures/Kubernetes/di.php'
    - '%kernel.project_dir%/vendor/teknoo/east-paas/infrastructures/Docker/di.php'
    - '%kernel.project_dir%/vendor/teknoo/east-paas/infrastructures/Composer/di.php'
    - '%kernel.project_dir%/vendor/teknoo/east-paas/infrastructures/Symfony/Components/di.php'
    - '%kernel.project_dir%/config/di.php'
  import:
