framework:
    messenger:
        transports:
            app_message_job: '%env(MESSENGER_JOB_TRANSPORT_DSN)%'

        routing:
            Teknoo\East\Paas\Infrastructures\Symfony\Messenger\Message\Job: 'app_message_job'
